// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PhiStudio",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "PhiStudio",
            targets: ["AppModule"],
            bundleIdentifier: "com.phix.phistudio",
            teamIdentifier: "VUW8FV5HN5",
            displayVersion: "0.0.1",
            bundleVersion: "4",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "添加曲绘🌟"),
                .mediaLibrary(purposeString: "添加音乐🎧")
            ]
        )
    ],
    dependencies: [
        .package(url: "https://gitee.com/spm_mirror/ZIPFoundation", "0.9.9"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ZIPFoundation", package: "zipfoundation")
            ],
            path: "."
        )
    ]
)
